### ISSUE TITLE
Warning: array_merge(): Argument #2 is not an array in app/code/core/Mage/Core/Model/Config.php on line 851

### ISSUE THREAD

**Issue by razbakov** [EcomDev/EcomDev_LayoutCompiler#2]
Warning: array_merge(): Argument # 2 is not an array in app/code/core/Mage/Core/Model/Config.php on line 851

Magento: 1.9.2.0 CE

Backtrace:

```
#0 [internal function]: mageCoreErrorHandler(2, 'array_merge(): ...', '/var/www/html/...', 851, Array)
#1 app/code/core/Mage/Core/Model/Config.php(851): array_merge(Array, NULL)
#2 app/code/core/Mage/Core/Model/Config.php(812): Mage_Core_Model_Config->_sortModuleDepends(Array)
#3 app/code/core/Mage/Core/Model/Config.php(315): Mage_Core_Model_Config->_loadDeclaredModules()
#4 app/code/core/Mage/Core/Model/App.php(425): Mage_Core_Model_Config->loadModules()
#5 app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Model_App->_initModules()
#6 app/Mage.php(684): Mage_Core_Model_App->run(Array)
#7 index.php(84): Mage::run('', 'store')
#8 {main}
```

**Comment by razbakov** [comment]
i think there is a check missing in core:

```
if(is_array($modules[$depend]['depends'])) {
    $depends = array_merge($depends, $modules[$depend]['depends']);
}
```

or maybe it is connected to #3
