### ISSUE TITLE
Module "EcomDev_LayoutCompilerTest" cannot depend on "EcomDev_PHPUnit".

### ISSUE THREAD

**Issue by razbakov** [EcomDev/EcomDev_LayoutCompiler#3]
Backtrace:

```
#0 app/code/core/Mage/Core/Model/Config.php(876): Mage::throwException('Module "EcomDev...')
#1 app/code/core/Mage/Core/Model/Config.php(812): Mage_Core_Model_Config->_sortModuleDepends(Array)
#2 app/code/core/Mage/Core/Model/Config.php(315): Mage_Core_Model_Config->_loadDeclaredModules()
#3 app/code/core/Mage/Core/Model/App.php(425): Mage_Core_Model_Config->loadModules()
#4 app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Model_App->_initModules()
#5 app/Mage.php(684): Mage_Core_Model_App->run(Array)
#6 index.php(84): Mage::run('', 'store')
#7 {main}
```

I would suggest either add EcomDev_PHPUnit as dependency to composer.json or remove it from EcomDev_LayoutCompilerTest.xml.

**Comment by IvanChepurnyi** [comment]
That's true an issue, as for production deployment EcomDev_PHPUnit is not installed.
